Fix crash bug in navigation library
java.lang.IllegalStateException: You must call setGraph() before calling getGraph()

when tabbing on bottom navigation view after
device changing theme from status bar which is considered configuration change like rotation